version: '3.7'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"  # Porta LocalStack
      - "4572:4572"  # Porta S3
    environment:
      SERVICES: s3       
      DEFAULT_REGION: us-east-1
      BUCKET_NAME: certificados
      AWS_ACCESS_KEY_ID: access-key
      AWS_SECRET_ACCESS_KEY: access-key-secret
    volumes:
      - ./localstack:/var/lib/localstack

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017